// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.11.2
// source: proto/hotel/hotel.proto

package hotelproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Hotel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HotelID  int64   `protobuf:"varint,1,opt,name=hotelID,proto3" json:"hotelID,omitempty"`
	Name     string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Location string  `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Rating   float64 `protobuf:"fixed64,4,opt,name=rating,proto3" json:"rating,omitempty"`
	Address  string  `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *Hotel) Reset() {
	*x = Hotel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hotel_hotel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hotel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hotel) ProtoMessage() {}

func (x *Hotel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotel_hotel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hotel.ProtoReflect.Descriptor instead.
func (*Hotel) Descriptor() ([]byte, []int) {
	return file_proto_hotel_hotel_proto_rawDescGZIP(), []int{0}
}

func (x *Hotel) GetHotelID() int64 {
	if x != nil {
		return x.HotelID
	}
	return 0
}

func (x *Hotel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Hotel) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Hotel) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Hotel) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type CreateHotelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Location string  `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Rating   float64 `protobuf:"fixed64,3,opt,name=rating,proto3" json:"rating,omitempty"`
	Address  string  `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *CreateHotelRequest) Reset() {
	*x = CreateHotelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hotel_hotel_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateHotelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHotelRequest) ProtoMessage() {}

func (x *CreateHotelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotel_hotel_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHotelRequest.ProtoReflect.Descriptor instead.
func (*CreateHotelRequest) Descriptor() ([]byte, []int) {
	return file_proto_hotel_hotel_proto_rawDescGZIP(), []int{1}
}

func (x *CreateHotelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateHotelRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CreateHotelRequest) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *CreateHotelRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type CreateHotelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hotel *Hotel `protobuf:"bytes,1,opt,name=hotel,proto3" json:"hotel,omitempty"`
}

func (x *CreateHotelResponse) Reset() {
	*x = CreateHotelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hotel_hotel_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateHotelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHotelResponse) ProtoMessage() {}

func (x *CreateHotelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotel_hotel_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHotelResponse.ProtoReflect.Descriptor instead.
func (*CreateHotelResponse) Descriptor() ([]byte, []int) {
	return file_proto_hotel_hotel_proto_rawDescGZIP(), []int{2}
}

func (x *CreateHotelResponse) GetHotel() *Hotel {
	if x != nil {
		return x.Hotel
	}
	return nil
}

type GetHotelsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetHotelsRequest) Reset() {
	*x = GetHotelsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hotel_hotel_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHotelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHotelsRequest) ProtoMessage() {}

func (x *GetHotelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotel_hotel_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHotelsRequest.ProtoReflect.Descriptor instead.
func (*GetHotelsRequest) Descriptor() ([]byte, []int) {
	return file_proto_hotel_hotel_proto_rawDescGZIP(), []int{3}
}

type GetHotelsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hotels []*Hotel `protobuf:"bytes,1,rep,name=hotels,proto3" json:"hotels,omitempty"`
}

func (x *GetHotelsResponse) Reset() {
	*x = GetHotelsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hotel_hotel_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHotelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHotelsResponse) ProtoMessage() {}

func (x *GetHotelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotel_hotel_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHotelsResponse.ProtoReflect.Descriptor instead.
func (*GetHotelsResponse) Descriptor() ([]byte, []int) {
	return file_proto_hotel_hotel_proto_rawDescGZIP(), []int{4}
}

func (x *GetHotelsResponse) GetHotels() []*Hotel {
	if x != nil {
		return x.Hotels
	}
	return nil
}

type GetHotelDetailsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HotelID int64 `protobuf:"varint,1,opt,name=hotelID,proto3" json:"hotelID,omitempty"`
}

func (x *GetHotelDetailsRequest) Reset() {
	*x = GetHotelDetailsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hotel_hotel_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHotelDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHotelDetailsRequest) ProtoMessage() {}

func (x *GetHotelDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotel_hotel_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHotelDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetHotelDetailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_hotel_hotel_proto_rawDescGZIP(), []int{5}
}

func (x *GetHotelDetailsRequest) GetHotelID() int64 {
	if x != nil {
		return x.HotelID
	}
	return 0
}

type Room struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomType      string  `protobuf:"bytes,1,opt,name=roomType,proto3" json:"roomType,omitempty"`
	PricePerNight float64 `protobuf:"fixed64,2,opt,name=pricePerNight,proto3" json:"pricePerNight,omitempty"`
	Availability  bool    `protobuf:"varint,3,opt,name=availability,proto3" json:"availability,omitempty"`
}

func (x *Room) Reset() {
	*x = Room{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hotel_hotel_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotel_hotel_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_proto_hotel_hotel_proto_rawDescGZIP(), []int{6}
}

func (x *Room) GetRoomType() string {
	if x != nil {
		return x.RoomType
	}
	return ""
}

func (x *Room) GetPricePerNight() float64 {
	if x != nil {
		return x.PricePerNight
	}
	return 0
}

func (x *Room) GetAvailability() bool {
	if x != nil {
		return x.Availability
	}
	return false
}

type GetHotelDetailsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HotelID  int64   `protobuf:"varint,1,opt,name=hotelID,proto3" json:"hotelID,omitempty"`
	Name     string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Location string  `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Rating   float64 `protobuf:"fixed64,4,opt,name=rating,proto3" json:"rating,omitempty"`
	Address  string  `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Rooms    []*Room `protobuf:"bytes,6,rep,name=rooms,proto3" json:"rooms,omitempty"`
}

func (x *GetHotelDetailsResponse) Reset() {
	*x = GetHotelDetailsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hotel_hotel_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHotelDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHotelDetailsResponse) ProtoMessage() {}

func (x *GetHotelDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotel_hotel_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHotelDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetHotelDetailsResponse) Descriptor() ([]byte, []int) {
	return file_proto_hotel_hotel_proto_rawDescGZIP(), []int{7}
}

func (x *GetHotelDetailsResponse) GetHotelID() int64 {
	if x != nil {
		return x.HotelID
	}
	return 0
}

func (x *GetHotelDetailsResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetHotelDetailsResponse) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *GetHotelDetailsResponse) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *GetHotelDetailsResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetHotelDetailsResponse) GetRooms() []*Room {
	if x != nil {
		return x.Rooms
	}
	return nil
}

type CheckRoomAvailabilityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HotelID int64 `protobuf:"varint,1,opt,name=hotelID,proto3" json:"hotelID,omitempty"`
}

func (x *CheckRoomAvailabilityRequest) Reset() {
	*x = CheckRoomAvailabilityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hotel_hotel_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckRoomAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRoomAvailabilityRequest) ProtoMessage() {}

func (x *CheckRoomAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotel_hotel_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRoomAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*CheckRoomAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_proto_hotel_hotel_proto_rawDescGZIP(), []int{8}
}

func (x *CheckRoomAvailabilityRequest) GetHotelID() int64 {
	if x != nil {
		return x.HotelID
	}
	return 0
}

type RoomAvailability struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomType       string `protobuf:"bytes,1,opt,name=roomType,proto3" json:"roomType,omitempty"`
	AvailableRooms bool   `protobuf:"varint,2,opt,name=availableRooms,proto3" json:"availableRooms,omitempty"`
}

func (x *RoomAvailability) Reset() {
	*x = RoomAvailability{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hotel_hotel_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomAvailability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomAvailability) ProtoMessage() {}

func (x *RoomAvailability) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotel_hotel_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomAvailability.ProtoReflect.Descriptor instead.
func (*RoomAvailability) Descriptor() ([]byte, []int) {
	return file_proto_hotel_hotel_proto_rawDescGZIP(), []int{9}
}

func (x *RoomAvailability) GetRoomType() string {
	if x != nil {
		return x.RoomType
	}
	return ""
}

func (x *RoomAvailability) GetAvailableRooms() bool {
	if x != nil {
		return x.AvailableRooms
	}
	return false
}

type CheckRoomAvailabilityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomAvailabilities []*RoomAvailability `protobuf:"bytes,1,rep,name=roomAvailabilities,proto3" json:"roomAvailabilities,omitempty"`
}

func (x *CheckRoomAvailabilityResponse) Reset() {
	*x = CheckRoomAvailabilityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hotel_hotel_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckRoomAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRoomAvailabilityResponse) ProtoMessage() {}

func (x *CheckRoomAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotel_hotel_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRoomAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*CheckRoomAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_proto_hotel_hotel_proto_rawDescGZIP(), []int{10}
}

func (x *CheckRoomAvailabilityResponse) GetRoomAvailabilities() []*RoomAvailability {
	if x != nil {
		return x.RoomAvailabilities
	}
	return nil
}

type DeleteHotelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HotelID int64 `protobuf:"varint,1,opt,name=hotelID,proto3" json:"hotelID,omitempty"`
}

func (x *DeleteHotelRequest) Reset() {
	*x = DeleteHotelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hotel_hotel_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteHotelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHotelRequest) ProtoMessage() {}

func (x *DeleteHotelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotel_hotel_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHotelRequest.ProtoReflect.Descriptor instead.
func (*DeleteHotelRequest) Descriptor() ([]byte, []int) {
	return file_proto_hotel_hotel_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteHotelRequest) GetHotelID() int64 {
	if x != nil {
		return x.HotelID
	}
	return 0
}

type DeleteHotelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteHotelResponse) Reset() {
	*x = DeleteHotelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hotel_hotel_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteHotelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHotelResponse) ProtoMessage() {}

func (x *DeleteHotelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotel_hotel_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHotelResponse.ProtoReflect.Descriptor instead.
func (*DeleteHotelResponse) Descriptor() ([]byte, []int) {
	return file_proto_hotel_hotel_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteHotelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Rooms
type Rooms struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomID        int64   `protobuf:"varint,1,opt,name=roomID,proto3" json:"roomID,omitempty"`
	HotelID       int64   `protobuf:"varint,2,opt,name=hotelID,proto3" json:"hotelID,omitempty"`
	RoomType      string  `protobuf:"bytes,3,opt,name=roomType,proto3" json:"roomType,omitempty"`
	PricePerNight float64 `protobuf:"fixed64,4,opt,name=pricePerNight,proto3" json:"pricePerNight,omitempty"`
	Availability  bool    `protobuf:"varint,5,opt,name=availability,proto3" json:"availability,omitempty"`
}

func (x *Rooms) Reset() {
	*x = Rooms{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hotel_hotel_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rooms) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rooms) ProtoMessage() {}

func (x *Rooms) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotel_hotel_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rooms.ProtoReflect.Descriptor instead.
func (*Rooms) Descriptor() ([]byte, []int) {
	return file_proto_hotel_hotel_proto_rawDescGZIP(), []int{13}
}

func (x *Rooms) GetRoomID() int64 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

func (x *Rooms) GetHotelID() int64 {
	if x != nil {
		return x.HotelID
	}
	return 0
}

func (x *Rooms) GetRoomType() string {
	if x != nil {
		return x.RoomType
	}
	return ""
}

func (x *Rooms) GetPricePerNight() float64 {
	if x != nil {
		return x.PricePerNight
	}
	return 0
}

func (x *Rooms) GetAvailability() bool {
	if x != nil {
		return x.Availability
	}
	return false
}

type CreateRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HotelID       int64   `protobuf:"varint,1,opt,name=hotelID,proto3" json:"hotelID,omitempty"`
	RoomType      string  `protobuf:"bytes,2,opt,name=roomType,proto3" json:"roomType,omitempty"`
	PricePerNight float64 `protobuf:"fixed64,3,opt,name=pricePerNight,proto3" json:"pricePerNight,omitempty"`
	Availability  bool    `protobuf:"varint,4,opt,name=availability,proto3" json:"availability,omitempty"`
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hotel_hotel_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotel_hotel_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_hotel_hotel_proto_rawDescGZIP(), []int{14}
}

func (x *CreateRoomRequest) GetHotelID() int64 {
	if x != nil {
		return x.HotelID
	}
	return 0
}

func (x *CreateRoomRequest) GetRoomType() string {
	if x != nil {
		return x.RoomType
	}
	return ""
}

func (x *CreateRoomRequest) GetPricePerNight() float64 {
	if x != nil {
		return x.PricePerNight
	}
	return 0
}

func (x *CreateRoomRequest) GetAvailability() bool {
	if x != nil {
		return x.Availability
	}
	return false
}

type CreateRoomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Room *Rooms `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
}

func (x *CreateRoomResponse) Reset() {
	*x = CreateRoomResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hotel_hotel_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomResponse) ProtoMessage() {}

func (x *CreateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotel_hotel_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomResponse.ProtoReflect.Descriptor instead.
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return file_proto_hotel_hotel_proto_rawDescGZIP(), []int{15}
}

func (x *CreateRoomResponse) GetRoom() *Rooms {
	if x != nil {
		return x.Room
	}
	return nil
}

type GetRoomsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HotelID int64 `protobuf:"varint,1,opt,name=hotelID,proto3" json:"hotelID,omitempty"`
}

func (x *GetRoomsRequest) Reset() {
	*x = GetRoomsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hotel_hotel_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRoomsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomsRequest) ProtoMessage() {}

func (x *GetRoomsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotel_hotel_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomsRequest.ProtoReflect.Descriptor instead.
func (*GetRoomsRequest) Descriptor() ([]byte, []int) {
	return file_proto_hotel_hotel_proto_rawDescGZIP(), []int{16}
}

func (x *GetRoomsRequest) GetHotelID() int64 {
	if x != nil {
		return x.HotelID
	}
	return 0
}

type GetRoomsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rooms []*Rooms `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
}

func (x *GetRoomsResponse) Reset() {
	*x = GetRoomsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hotel_hotel_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRoomsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomsResponse) ProtoMessage() {}

func (x *GetRoomsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotel_hotel_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomsResponse.ProtoReflect.Descriptor instead.
func (*GetRoomsResponse) Descriptor() ([]byte, []int) {
	return file_proto_hotel_hotel_proto_rawDescGZIP(), []int{17}
}

func (x *GetRoomsResponse) GetRooms() []*Rooms {
	if x != nil {
		return x.Rooms
	}
	return nil
}

type UpdateRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomID        int64   `protobuf:"varint,1,opt,name=roomID,proto3" json:"roomID,omitempty"`
	RoomType      string  `protobuf:"bytes,2,opt,name=roomType,proto3" json:"roomType,omitempty"`
	PricePerNight float64 `protobuf:"fixed64,3,opt,name=pricePerNight,proto3" json:"pricePerNight,omitempty"`
	Availability  bool    `protobuf:"varint,4,opt,name=availability,proto3" json:"availability,omitempty"`
}

func (x *UpdateRoomRequest) Reset() {
	*x = UpdateRoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hotel_hotel_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoomRequest) ProtoMessage() {}

func (x *UpdateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotel_hotel_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoomRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_hotel_hotel_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateRoomRequest) GetRoomID() int64 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

func (x *UpdateRoomRequest) GetRoomType() string {
	if x != nil {
		return x.RoomType
	}
	return ""
}

func (x *UpdateRoomRequest) GetPricePerNight() float64 {
	if x != nil {
		return x.PricePerNight
	}
	return 0
}

func (x *UpdateRoomRequest) GetAvailability() bool {
	if x != nil {
		return x.Availability
	}
	return false
}

type UpdateRoomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Room *Rooms `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
}

func (x *UpdateRoomResponse) Reset() {
	*x = UpdateRoomResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hotel_hotel_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoomResponse) ProtoMessage() {}

func (x *UpdateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotel_hotel_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoomResponse.ProtoReflect.Descriptor instead.
func (*UpdateRoomResponse) Descriptor() ([]byte, []int) {
	return file_proto_hotel_hotel_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateRoomResponse) GetRoom() *Rooms {
	if x != nil {
		return x.Room
	}
	return nil
}

type DeleteRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomID int64 `protobuf:"varint,1,opt,name=roomID,proto3" json:"roomID,omitempty"`
}

func (x *DeleteRoomRequest) Reset() {
	*x = DeleteRoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hotel_hotel_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoomRequest) ProtoMessage() {}

func (x *DeleteRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotel_hotel_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoomRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_hotel_hotel_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteRoomRequest) GetRoomID() int64 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

type DeleteRoomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteRoomResponse) Reset() {
	*x = DeleteRoomResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hotel_hotel_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoomResponse) ProtoMessage() {}

func (x *DeleteRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotel_hotel_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoomResponse.ProtoReflect.Descriptor instead.
func (*DeleteRoomResponse) Descriptor() ([]byte, []int) {
	return file_proto_hotel_hotel_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteRoomResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetRoomDetailsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomID  int64 `protobuf:"varint,1,opt,name=roomID,proto3" json:"roomID,omitempty"`
	HotelID int64 `protobuf:"varint,2,opt,name=hotelID,proto3" json:"hotelID,omitempty"`
}

func (x *GetRoomDetailsRequest) Reset() {
	*x = GetRoomDetailsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hotel_hotel_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRoomDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomDetailsRequest) ProtoMessage() {}

func (x *GetRoomDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotel_hotel_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetRoomDetailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_hotel_hotel_proto_rawDescGZIP(), []int{22}
}

func (x *GetRoomDetailsRequest) GetRoomID() int64 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

func (x *GetRoomDetailsRequest) GetHotelID() int64 {
	if x != nil {
		return x.HotelID
	}
	return 0
}

type GetRoomDetailsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomID        int64   `protobuf:"varint,1,opt,name=roomID,proto3" json:"roomID,omitempty"`
	HotelID       int64   `protobuf:"varint,2,opt,name=hotelID,proto3" json:"hotelID,omitempty"`
	RoomType      string  `protobuf:"bytes,3,opt,name=roomType,proto3" json:"roomType,omitempty"`
	PricePerNight float64 `protobuf:"fixed64,4,opt,name=pricePerNight,proto3" json:"pricePerNight,omitempty"`
	Availability  bool    `protobuf:"varint,5,opt,name=availability,proto3" json:"availability,omitempty"`
}

func (x *GetRoomDetailsResponse) Reset() {
	*x = GetRoomDetailsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hotel_hotel_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRoomDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomDetailsResponse) ProtoMessage() {}

func (x *GetRoomDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotel_hotel_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetRoomDetailsResponse) Descriptor() ([]byte, []int) {
	return file_proto_hotel_hotel_proto_rawDescGZIP(), []int{23}
}

func (x *GetRoomDetailsResponse) GetRoomID() int64 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

func (x *GetRoomDetailsResponse) GetHotelID() int64 {
	if x != nil {
		return x.HotelID
	}
	return 0
}

func (x *GetRoomDetailsResponse) GetRoomType() string {
	if x != nil {
		return x.RoomType
	}
	return ""
}

func (x *GetRoomDetailsResponse) GetPricePerNight() float64 {
	if x != nil {
		return x.PricePerNight
	}
	return 0
}

func (x *GetRoomDetailsResponse) GetAvailability() bool {
	if x != nil {
		return x.Availability
	}
	return false
}

var File_proto_hotel_hotel_proto protoreflect.FileDescriptor

var file_proto_hotel_hotel_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x2f, 0x68, 0x6f,
	0x74, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x83, 0x01, 0x0a, 0x05, 0x48, 0x6f,
	0x74, 0x65, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x49, 0x44, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x72,
	0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22,
	0x76, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x33, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c,
	0x0a, 0x05, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e,
	0x48, 0x6f, 0x74, 0x65, 0x6c, 0x52, 0x05, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x22, 0x12, 0x0a, 0x10,
	0x47, 0x65, 0x74, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x33, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x06, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x52, 0x06, 0x68,
	0x6f, 0x74, 0x65, 0x6c, 0x73, 0x22, 0x32, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x74, 0x65,
	0x6c, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x49, 0x44, 0x22, 0x6c, 0x0a, 0x04, 0x52, 0x6f, 0x6f,
	0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x24, 0x0a,
	0x0d, 0x70, 0x72, 0x69, 0x63, 0x65, 0x50, 0x65, 0x72, 0x4e, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x0d, 0x70, 0x72, 0x69, 0x63, 0x65, 0x50, 0x65, 0x72, 0x4e, 0x69,
	0x67, 0x68, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c,
	0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x61, 0x76, 0x61, 0x69, 0x6c,
	0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x22, 0xb2, 0x01, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x48,
	0x6f, 0x74, 0x65, 0x6c, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x49, 0x44, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x72,
	0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x1b, 0x0a, 0x05, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05,
	0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x05, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x22, 0x38, 0x0a, 0x1c,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x6f, 0x6f, 0x6d, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62,
	0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x68, 0x6f, 0x74, 0x65, 0x6c, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x68,
	0x6f, 0x74, 0x65, 0x6c, 0x49, 0x44, 0x22, 0x56, 0x0a, 0x10, 0x52, 0x6f, 0x6f, 0x6d, 0x41, 0x76,
	0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f,
	0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f,
	0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61,
	0x62, 0x6c, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e,
	0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x22, 0x62,
	0x0a, 0x1d, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x6f, 0x6f, 0x6d, 0x41, 0x76, 0x61, 0x69, 0x6c,
	0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x41, 0x0a, 0x12, 0x72, 0x6f, 0x6f, 0x6d, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c,
	0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x52, 0x6f,
	0x6f, 0x6d, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x12,
	0x72, 0x6f, 0x6f, 0x6d, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69,
	0x65, 0x73, 0x22, 0x2e, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x6f, 0x74, 0x65,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x6f, 0x74, 0x65,
	0x6c, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x68, 0x6f, 0x74, 0x65, 0x6c,
	0x49, 0x44, 0x22, 0x2f, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x6f, 0x74, 0x65,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x22, 0x9f, 0x01, 0x0a, 0x05, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72,
	0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x49, 0x44, 0x12,
	0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x50, 0x65, 0x72, 0x4e, 0x69, 0x67, 0x68, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x0d, 0x70, 0x72, 0x69, 0x63, 0x65, 0x50, 0x65, 0x72, 0x4e, 0x69, 0x67, 0x68,
	0x74, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74,
	0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62,
	0x69, 0x6c, 0x69, 0x74, 0x79, 0x22, 0x93, 0x01, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x68,
	0x6f, 0x74, 0x65, 0x6c, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x68, 0x6f,
	0x74, 0x65, 0x6c, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x24, 0x0a, 0x0d, 0x70, 0x72, 0x69, 0x63, 0x65, 0x50, 0x65, 0x72, 0x4e, 0x69, 0x67,
	0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0d, 0x70, 0x72, 0x69, 0x63, 0x65, 0x50,
	0x65, 0x72, 0x4e, 0x69, 0x67, 0x68, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x76, 0x61, 0x69, 0x6c,
	0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x61,
	0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x22, 0x30, 0x0a, 0x12, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1a, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x06, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x22, 0x2b, 0x0a,
	0x0f, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x49, 0x44, 0x22, 0x30, 0x0a, 0x10, 0x47, 0x65,
	0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c,
	0x0a, 0x05, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x06, 0x2e,
	0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x52, 0x05, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x22, 0x91, 0x01, 0x0a,
	0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f,
	0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f,
	0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x70, 0x72, 0x69, 0x63, 0x65, 0x50,
	0x65, 0x72, 0x4e, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0d, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x50, 0x65, 0x72, 0x4e, 0x69, 0x67, 0x68, 0x74, 0x12, 0x22, 0x0a, 0x0c,
	0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0c, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79,
	0x22, 0x30, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x52, 0x04, 0x72, 0x6f,
	0x6f, 0x6d, 0x22, 0x2b, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x22,
	0x2e, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22,
	0x49, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44,
	0x12, 0x18, 0x0a, 0x07, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x49, 0x44, 0x22, 0xb0, 0x01, 0x0a, 0x16, 0x47,
	0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x12, 0x18, 0x0a,
	0x07, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x68, 0x6f, 0x74, 0x65, 0x6c, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x70, 0x72, 0x69, 0x63, 0x65, 0x50, 0x65, 0x72, 0x4e,
	0x69, 0x67, 0x68, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0d, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x50, 0x65, 0x72, 0x4e, 0x69, 0x67, 0x68, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x76, 0x61,
	0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0c, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x32, 0xea, 0x04,
	0x0a, 0x0c, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x38,
	0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x12, 0x13, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x14, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x74, 0x65, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x48,
	0x6f, 0x74, 0x65, 0x6c, 0x73, 0x12, 0x11, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x74, 0x65, 0x6c,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x6f,
	0x74, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0f,
	0x47, 0x65, 0x74, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12,
	0x17, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x6f,
	0x74, 0x65, 0x6c, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x56, 0x0a, 0x15, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x6f, 0x6f, 0x6d, 0x41,
	0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x1d, 0x2e, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x52, 0x6f, 0x6f, 0x6d, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c,
	0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x52, 0x6f, 0x6f, 0x6d, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x0b, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x12, 0x13, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f,
	0x6f, 0x6d, 0x12, 0x12, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x0b, 0x47,
	0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x42, 0x79, 0x49, 0x44, 0x12, 0x16, 0x2e, 0x47, 0x65, 0x74,
	0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x17, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x08, 0x47,
	0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x12, 0x10, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f,
	0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x47, 0x65, 0x74, 0x52,
	0x6f, 0x6f, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0a,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x12, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x6f, 0x6f,
	0x6d, 0x12, 0x12, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x6f,
	0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f,
	0x68, 0x6f, 0x74, 0x65, 0x6c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_hotel_hotel_proto_rawDescOnce sync.Once
	file_proto_hotel_hotel_proto_rawDescData = file_proto_hotel_hotel_proto_rawDesc
)

func file_proto_hotel_hotel_proto_rawDescGZIP() []byte {
	file_proto_hotel_hotel_proto_rawDescOnce.Do(func() {
		file_proto_hotel_hotel_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_hotel_hotel_proto_rawDescData)
	})
	return file_proto_hotel_hotel_proto_rawDescData
}

var file_proto_hotel_hotel_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_proto_hotel_hotel_proto_goTypes = []any{
	(*Hotel)(nil),                         // 0: Hotel
	(*CreateHotelRequest)(nil),            // 1: CreateHotelRequest
	(*CreateHotelResponse)(nil),           // 2: CreateHotelResponse
	(*GetHotelsRequest)(nil),              // 3: GetHotelsRequest
	(*GetHotelsResponse)(nil),             // 4: GetHotelsResponse
	(*GetHotelDetailsRequest)(nil),        // 5: GetHotelDetailsRequest
	(*Room)(nil),                          // 6: Room
	(*GetHotelDetailsResponse)(nil),       // 7: GetHotelDetailsResponse
	(*CheckRoomAvailabilityRequest)(nil),  // 8: CheckRoomAvailabilityRequest
	(*RoomAvailability)(nil),              // 9: RoomAvailability
	(*CheckRoomAvailabilityResponse)(nil), // 10: CheckRoomAvailabilityResponse
	(*DeleteHotelRequest)(nil),            // 11: DeleteHotelRequest
	(*DeleteHotelResponse)(nil),           // 12: DeleteHotelResponse
	(*Rooms)(nil),                         // 13: Rooms
	(*CreateRoomRequest)(nil),             // 14: CreateRoomRequest
	(*CreateRoomResponse)(nil),            // 15: CreateRoomResponse
	(*GetRoomsRequest)(nil),               // 16: GetRoomsRequest
	(*GetRoomsResponse)(nil),              // 17: GetRoomsResponse
	(*UpdateRoomRequest)(nil),             // 18: UpdateRoomRequest
	(*UpdateRoomResponse)(nil),            // 19: UpdateRoomResponse
	(*DeleteRoomRequest)(nil),             // 20: DeleteRoomRequest
	(*DeleteRoomResponse)(nil),            // 21: DeleteRoomResponse
	(*GetRoomDetailsRequest)(nil),         // 22: GetRoomDetailsRequest
	(*GetRoomDetailsResponse)(nil),        // 23: GetRoomDetailsResponse
}
var file_proto_hotel_hotel_proto_depIdxs = []int32{
	0,  // 0: CreateHotelResponse.hotel:type_name -> Hotel
	0,  // 1: GetHotelsResponse.hotels:type_name -> Hotel
	6,  // 2: GetHotelDetailsResponse.rooms:type_name -> Room
	9,  // 3: CheckRoomAvailabilityResponse.roomAvailabilities:type_name -> RoomAvailability
	13, // 4: CreateRoomResponse.room:type_name -> Rooms
	13, // 5: GetRoomsResponse.rooms:type_name -> Rooms
	13, // 6: UpdateRoomResponse.room:type_name -> Rooms
	1,  // 7: HotelService.CreateHotel:input_type -> CreateHotelRequest
	3,  // 8: HotelService.GetHotels:input_type -> GetHotelsRequest
	5,  // 9: HotelService.GetHotelDetails:input_type -> GetHotelDetailsRequest
	8,  // 10: HotelService.CheckRoomAvailability:input_type -> CheckRoomAvailabilityRequest
	11, // 11: HotelService.DeleteHotel:input_type -> DeleteHotelRequest
	14, // 12: HotelService.CreateRoom:input_type -> CreateRoomRequest
	22, // 13: HotelService.GetRoomByID:input_type -> GetRoomDetailsRequest
	16, // 14: HotelService.GetRooms:input_type -> GetRoomsRequest
	18, // 15: HotelService.UpdateRoom:input_type -> UpdateRoomRequest
	20, // 16: HotelService.DeleteRoom:input_type -> DeleteRoomRequest
	2,  // 17: HotelService.CreateHotel:output_type -> CreateHotelResponse
	4,  // 18: HotelService.GetHotels:output_type -> GetHotelsResponse
	7,  // 19: HotelService.GetHotelDetails:output_type -> GetHotelDetailsResponse
	10, // 20: HotelService.CheckRoomAvailability:output_type -> CheckRoomAvailabilityResponse
	12, // 21: HotelService.DeleteHotel:output_type -> DeleteHotelResponse
	15, // 22: HotelService.CreateRoom:output_type -> CreateRoomResponse
	23, // 23: HotelService.GetRoomByID:output_type -> GetRoomDetailsResponse
	17, // 24: HotelService.GetRooms:output_type -> GetRoomsResponse
	19, // 25: HotelService.UpdateRoom:output_type -> UpdateRoomResponse
	21, // 26: HotelService.DeleteRoom:output_type -> DeleteRoomResponse
	17, // [17:27] is the sub-list for method output_type
	7,  // [7:17] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_hotel_hotel_proto_init() }
func file_proto_hotel_hotel_proto_init() {
	if File_proto_hotel_hotel_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_hotel_hotel_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Hotel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hotel_hotel_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreateHotelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hotel_hotel_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CreateHotelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hotel_hotel_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetHotelsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hotel_hotel_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetHotelsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hotel_hotel_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetHotelDetailsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hotel_hotel_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*Room); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hotel_hotel_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GetHotelDetailsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hotel_hotel_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*CheckRoomAvailabilityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hotel_hotel_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*RoomAvailability); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hotel_hotel_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*CheckRoomAvailabilityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hotel_hotel_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteHotelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hotel_hotel_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteHotelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hotel_hotel_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*Rooms); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hotel_hotel_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*CreateRoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hotel_hotel_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*CreateRoomResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hotel_hotel_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*GetRoomsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hotel_hotel_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*GetRoomsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hotel_hotel_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateRoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hotel_hotel_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateRoomResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hotel_hotel_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteRoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hotel_hotel_proto_msgTypes[21].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteRoomResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hotel_hotel_proto_msgTypes[22].Exporter = func(v any, i int) any {
			switch v := v.(*GetRoomDetailsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hotel_hotel_proto_msgTypes[23].Exporter = func(v any, i int) any {
			switch v := v.(*GetRoomDetailsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_hotel_hotel_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_hotel_hotel_proto_goTypes,
		DependencyIndexes: file_proto_hotel_hotel_proto_depIdxs,
		MessageInfos:      file_proto_hotel_hotel_proto_msgTypes,
	}.Build()
	File_proto_hotel_hotel_proto = out.File
	file_proto_hotel_hotel_proto_rawDesc = nil
	file_proto_hotel_hotel_proto_goTypes = nil
	file_proto_hotel_hotel_proto_depIdxs = nil
}
